### ISSUE TITLE
Respond with PURL on creation endpoint

### ISSUE THREAD

**Issue by fabiante** [fabiante/persurl#23]
As API consumer I expect that the API returns the PURL I just created. This allows me to directly save / forward this to my application.

This requires updating this endpoint:

https://github.com/fabiante/persurl/blob/9a75f019555857c1d6c1f434f1fbfcd73812eb5a/api/openapi.yml#L59-L60

```yml
        200:
          description: PURL created or updated.
          content:
            application/json:
              schema:
                type: string
                example: http://localhost/r/your-domain/your-purl-name
```

- [ ] The returned URL should match the host used to communicate with this service.
